// ===== スプレッド定義 =====
const SPREADS = {
  tarot: [
    { id:"one_oracle", name:"ワンオラクル", count:1, layout:"flow",
      positions:[{label:"メッセージ", desc:"今のあなたへの、シンプルな一言。"}] },
    { id:"two_card", name:"ツーカード", count:2, layout:"flow",
      positions:[{label:"現状", desc:"今の状況を表します。"},
                 {label:"アドバイス", desc:"次に意識したいヒントです。"}] },
    { id:"three_card", name:"スリーカード", count:3, layout:"flow",
      positions:[{label:"過去", desc:"これまでの流れ、背景にあったこと。"},
                 {label:"現在", desc:"今まさに起きていること。"},
                 {label:"未来", desc:"このまま進んだ場合の見通し。"}] },
    { id:"hexagram", name:"ヘキサグラム", count:6, layout:"flow",
      positions:[{label:"自分の気持ち", desc:"あなたが今、心の中で感じていること。"},
                 {label:"相手の気持ち", desc:"相手が今、心の中で感じていること。"},
                 {label:"二人の関係の現状", desc:"今の二人の関係性を表します。"},
                 {label:"過去", desc:"ここまでの経緯。"},
                 {label:"未来", desc:"このまま進んだ場合の見通し。"},
                 {label:"最終的な結果", desc:"この関係が向かっていく先。"}] },
    { id:"two_choice", name:"二者択一", count:7, layout:"flow",
      positions:[{label:"現状", desc:"質問に対する、今の状況。"},
                 {label:"選択肢Aの現在", desc:"Aを選んだ場合の、今の状態。"},
                 {label:"選択肢Bの現在", desc:"Bを選んだ場合の、今の状態。"},
                 {label:"選択肢Aの未来", desc:"Aを選んだ場合に進んでいく先。"},
                 {label:"選択肢Bの未来", desc:"Bを選んだ場合に進んでいく先。"},
                 {label:"選択肢Aの結果", desc:"Aを選んだ場合の、最終的な結果。"},
                 {label:"選択肢Bの結果", desc:"Bを選んだ場合の、最終的な結果。"}] },
    { id:"celtic_cross", name:"ケルト十字", count:10, layout:"celtic",
      positions:[{label:"現状", desc:"今のあなたが置かれている状況。"},
                 {label:"障害", desc:"現状に働きかけている、課題や壁。"},
                 {label:"顕在意識", desc:"自分でも自覚している、目標や理想。"},
                 {label:"潜在意識", desc:"自分でも気づいていない、根底にある気持ち。"},
                 {label:"過去", desc:"ここまでの経緯、背景にあったこと。"},
                 {label:"未来", desc:"近い将来、訪れるであろう展開。"},
                 {label:"自分自身", desc:"この件に対する、あなた自身のスタンス。"},
                 {label:"周囲の影響", desc:"周りの人や環境からの影響。"},
                 {label:"希望と不安", desc:"心の中にある期待と、恐れの両方。"},
                 {label:"最終結果", desc:"物事が行き着く、最終的な結果。"}] },
    { id:"horoscope", name:"ホロスコープ", count:12, layout:"horoscope",
      positions:[{label:"①自分・性格", desc:"あなた自身のあり方。"},
                 {label:"②金運・所有", desc:"お金や持ち物にまつわること。"},
                 {label:"③コミュニケーション", desc:"日々のやり取りや学び。"},
                 {label:"④家庭・基盤", desc:"家族や、心の拠り所。"},
                 {label:"⑤恋愛・創造", desc:"恋愛や、楽しみ・創造の分野。"},
                 {label:"⑥健康・日常", desc:"体調や日々の暮らし。"},
                 {label:"⑦パートナーシップ", desc:"対等な関係、恋人や協力者。"},
                 {label:"⑧変容・継承", desc:"大きな変化や、受け継ぐもの。"},
                 {label:"⑨学び・遠方", desc:"学びや、遠くとの縁。"},
                 {label:"⑩社会性・仕事", desc:"仕事や、社会的な立場。"},
                 {label:"⑪友人・希望", desc:"友人関係や、これからの願い。"},
                 {label:"⑫潜在・秘密", desc:"まだ表に出ていない、内面のこと。"}] },
  ],
  lenormand: [
    { id:"one_oracle", name:"ワンオラクル", count:1, layout:"flow",
      positions:[{label:"メッセージ", desc:"今日のあなたへのメッセージ。"}] },
    { id:"two_card", name:"ツーカード", count:2, layout:"flow",
      positions:[{label:"主題", desc:"読み解く中心となるテーマ。"},
                 {label:"状態・修飾", desc:"1枚目を説明する、状態や性質。"}] },
    { id:"three_card", name:"スリーカード", count:3, layout:"flow",
      positions:[{label:"過去", desc:"これまでの流れ。"},
                 {label:"現在", desc:"今の状況。"},
                 {label:"未来", desc:"この先の展開。"}] },
    { id:"five_card", name:"ファイブカード", count:5, layout:"flow",
      positions:[{label:"過去", desc:"背景にあった出来事。"},
                 {label:"状況", desc:"今、中心にあるテーマ。"},
                 {label:"未来", desc:"この先の展開。"},
                 {label:"望ましい結果", desc:"目指すとよい方向性。"},
                 {label:"警告", desc:"気をつけておきたいこと。"}] },
    { id:"nine_card", name:"ナインカード", count:9, layout:"grid3",
      positions:[{label:"理想①", desc:"目指したい方向性。"},{label:"理想②", desc:"目指したい方向性。"},{label:"理想③", desc:"目指したい方向性。"},
                 {label:"現在①", desc:"今の状況。"},{label:"現在（核心）", desc:"今の中心的なテーマ。"},{label:"現在②", desc:"今の状況。"},
                 {label:"潜在意識①", desc:"自分でも気づいていない部分。"},{label:"潜在意識②", desc:"自分でも気づいていない部分。"},{label:"潜在意識③", desc:"自分でも気づいていない部分。"}] },
    { id:"grand_tableau", name:"グランタブロー", count:36, layout:"grand",
      positions: Array.from({length:36}, (_, i) => ({label: String(i+1), desc:"人生全体を映す、大きな展開の一枚。"})) },
  ],
  rune: [
    { id:"one_oracle", name:"ワンオラクル", count:1, layout:"flow",
      positions:[{label:"メッセージ", desc:"今のあなたへの、シンプルな一言。"}] },
    { id:"two_oracle", name:"ツーオラクル", count:2, layout:"flow",
      positions:[{label:"現状", desc:"今の状況。"},
                 {label:"アドバイス", desc:"次に意識したいヒント。"}] },
    { id:"three_rune", name:"スリールーン", count:3, layout:"flow",
      positions:[{label:"過去", desc:"これまでの流れ。"},
                 {label:"現在", desc:"今の状況。"},
                 {label:"未来", desc:"この先の展開。"}] },
    { id:"four_norns", name:"ノルンの予言", count:4, layout:"flow",
      positions:[{label:"状況", desc:"今起きていること。"},
                 {label:"課題", desc:"向き合う必要のあること。"},
                 {label:"対策", desc:"取るとよい行動。"},
                 {label:"結果", desc:"行き着く先。"}] },
    { id:"five_rune", name:"ファイブルーン", count:5, layout:"flow",
      positions:[{label:"現状", desc:"今の状況。"},
                 {label:"障害", desc:"立ちはだかる課題。"},
                 {label:"最近の影響", desc:"直近で影響を与えたこと。"},
                 {label:"近い未来", desc:"近々訪れる展開。"},
                 {label:"最終結果", desc:"行き着く最終的な結果。"}] },
  ],
};
SPREADS.marseille = SPREADS.tarot;
